[build]
  command = "npm install"
  publish = "landing"
  functions = "netlify-functions"

[functions]
  node_bundler = "esbuild"

[functions."generate-zip"]
  included_files = ["app/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
