[build]
  command = "echo 'No build step needed'"
  functions = "netlify-functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/generate-zip"
  to = "/.netlify/functions/generate-zip"
  status = 200
  force = true
